server:
  port: 8082
spring:
  application:
    name: agendamento
  profiles:
    active: dev
openapi:
  service:
    title: Agendamento API doc
    version: 1.0.0
    url: http://localhost:8080
springdoc:
  api-docs:
    path: /agendamento/v3/api-docs
  swagger-ui:
    path: /agendamento/swagger-ui.html
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true


