server:
  port: 8084
spring:
  application:
    name: profissional
  profiles:
    active: homol
openapi:
  service:
    title: Profissional API doc
    version: 1.0.0
    url: http://localhost:8080
springdoc:
  api-docs:
    path: /profissional/v3/api-docs
  swagger-ui:
    path: /profissional/swagger-ui.html
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true


