server:
  port: 8080
spring:
  application.name: gateway-api
  cloud:
    gateway:
      discovery:
        locator.enabled: true
        locator.lower-case-service-id: true
      httpclient:
        connect-timeout: 20000
        response-timeout: 7s
      routes:
        - id: cliente
          uri: lb://cliente
          predicates:
            - Path=/cliente/** , /cliente/v3/api-docs
          filters:
            - StripPrefix=1
        - id: profissional
          uri: lb://profissional
          predicates:
            - Path=/profissional/** , /profissional/v3/api-docs
          filters:
            - StripPrefix=1
        - id: servico
          uri: lb://servico
          predicates:
            - Path=/servico/** , /servico/v3/api-docs
          filters:
            - StripPrefix=1
        - id: agenda
          uri: lb://agenda
          predicates:
            - Path=/agenda/** , /agenda/v3/api-docs
          filters:
            - StripPrefix=1
        - id: produto
          uri: lb://produto
          predicates:
            - Path=/produto/** , /produto/v3/api-docs
          filters:
            - StripPrefix=1

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /cliente/v3/api-docs
        name: Clientes API
      - url: /profissional/v3/api-docs
        name: Profissionais API
      - url: /servico/v3/api-docs
        name: Servicos API
      - url: /agenda/v3/api-docs
        name: Agendamentos API
      - url: /produto/v3/api-docs
        name: Produtos API
eureka:
  client.service-url.defaultZone: http://localhost:8761/eureka
  client.service-url.fetch-registry: true
  client.service-url.register-with-eureka: true
