server:
  port: 8080
spring:
  application.name: gateway-api
  cloud:
    gateway:
      discovery:
        locator.enabled: true
        locator.lower-case-service-id: true
      httpclient:
        connect-timeout: 20000
        response-timeout: 7s
      routes:
        - id: clientes-api
          uri: lb://clientes-api
          predicates:
            - Path=/clientes/** , /clientes-api/v3/api-docs
          filters:
            - StripPrefix=1
        - id: profissionais-api
          uri: lb://profissionais-api
          predicates:
            - Path=/profissionais/** , /profissionais-api/v3/api-docs
          filters:
            - StripPrefix=1
        - id: servicos-api
          uri: lb://servicos-api
          predicates:
            - Path=/servicos/** , /servicos-api/v3/api-docs
          filters:
            - StripPrefix=1
        - id: agendamentos-api
          uri: lb://agendamentos-api
          predicates:
            - Path=/agendamentos/** , /agendamentos-api/v3/api-docs
          filters:
            - StripPrefix=1
        - id: produtos-api
          uri: lb://produtos-api
          predicates:
            - Path=/produtos/** , /produtos-api/v3/api-docs
          filters:
            - StripPrefix=1

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /clientes-api/v3/api-docs
        name: Clientes API
      - url: /profissionais-api/v3/api-docs
        name: Profissionais API
      - url: /servicos-api/v3/api-docs
        name: Servicos API
      - url: /agendamentos-api/v3/api-docs
        name: Agendamentos API
      - url: /produtos-api/v3/api-docs
        name: Produtos API
eureka:
  client.service-url.defaultZone: http://localhost:8761/eureka
  client.service-url.fetch-registry: true
  client.service-url.register-with-eureka: true
