server:
  port: 8083
spring:
  application:
    name: clientes-api
  profiles:
    active: dev
openapi:
  service:
    title: clientes-api doc
    version: 1.0.0
    url: http://localhost:8080

springdoc:
  api-docs:
    path: /clientes-api/v3/api-docs
  swagger-ui:
    path: /clientes-api/swagger-ui.html
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true


