server:
  port: 8083
spring:
  application:
    name: cliente
  profiles:
    active: homol
openapi:
  service:
    title: cliente doc
    version: 1.0.0
    url: http://localhost:8080

springdoc:
  api-docs:
    path: /cliente/v3/api-docs
  swagger-ui:
    path: /cliente/swagger-ui.html
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true


