server:
  port: 8081
spring:
  application:
    name: produto
  profiles:
    active: homol
openapi:
  service:
    title: Produto API doc
    version: 1.0.0
    url: http://localhost:8080
springdoc:
  api-docs:
    path: /produto/v3/api-docs
  swagger-ui:
    path: /produto/swagger-ui.html
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true


